// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjbwobaeflcpvkapyzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iamJ3b2JhZWZsY3B2a2FweXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzY0NDMsImV4cCI6MjA3MDIxMjQ0M30.n6e6Oq9sB596zskAnc7WedamGkhoX6AMoszrRVUPPZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});